#!/usr/bin/sh
set -eu

if [ $# -lt 2 ]; then
  >&2 printf 'Usage: %s <device> <command> [args]\n'
  >&2 printf 'Lock the given <device> and run <command> with <args>.\n'
  >&2 printf 'Unlike udevadm lock, the device can be either a /dev node, or a sysfs path.\n'
  >&2 printf 'The block device /dev node for <device> will be automatically appended to args.\n'
  exit 2
fi

device="$1"; shift

if [ -b "${device}" ]; then
  blkdev="${device}"
elif [ -e "${device}" ]; then
  blkdev="/dev/$(udevadm info -q name "${device}")"
elif [ -b "/dev/${device}" ]; then
  blkdev="/dev/${device}"
else
  blkdev="$(udevadm info -q name -p "${device}")"
fi

udevadm lock -d "${blkdev}" "$@" "${blkdev}"
