#!/usr/bin/sh
set -eu

if [ $# -ne 1 ] || [ "$1" = '--help' ]; then
  printf 'Usage: %s <partition>\n' "${0##*/}"
  exit 2
fi

# Something other than AES to increase the entropy in our security risk.
cipher_algo=twofish-xts-plain64
cipher_keysize=512
# authenticated encryption to ensure the integrity of the partition.
integrity_algo=hmac-sha256

blkdev="$1";shift
luks_label=lukshdrs

current_fstype="$(lsblk -r -o FSTYPE -d -n "${blkdev}")"
if [ -n "${current_fstype}" ]; then
  >&2 printf 'Error: %s already contains a file system of type %s!\n' "${blkdev}" "${current_fstype}"
  exit 1
fi
if [ -n "$(wipefs -n -p "${blkdev}")" ]; then
  >&2 printf 'Error: Device %s already contains something\n' "${blkdev}"
  >&2 wipefs -n "${blkdev}"
  exit 1
fi

keyfile_tmp="$(mktemp -t lukshdrs-temporary-keyfile-XXXXXXXX.bin)"
dd if=/dev/urandom bs=128 count=1 of="${keyfile_tmp}" status=none

printf 'Creating LUKS header on %s\n' "${blkdev}"
cryptsetup luksFormat \
  --batch-mode \
  --type luks2 \
  --key-file "${keyfile_tmp}" \
  --label "${luks_label}" \
  --cipher "${cipher_algo}" \
  --key-size "${cipher_keysize}" \
  --integrity "${integrity_algo}" \
  "${blkdev}"

printf 'Open newly formatted device %s as dm-crypt mapping %s\n' "${blkdev}" "${luks_label}"
cryptsetup open --key-file "${keyfile_tmp}" "${blkdev}" "${luks_label}"
crypt_dev="/dev/mapper/${luks_label}"
printf 'Format encrypted device %s as XFS\n' "${crypt_dev}"
udevadm lock -d "${crypt_dev}" mkfs.xfs -m rmapbt=1 -L "${luks_label}" "${crypt_dev}"
printf 'Disable dm-crypt mapping %s\n' "${luks_label}"
cryptsetup close "${luks_label}"

printf 'Enrolling FIDO2 key for encryption unlocking, you may need to enter your FIDO pin next\n'
systemd-cryptenroll --unlock-key-file="${keyfile_tmp}" \
  --fido2-device=auto \
  --wipe-slot=password \
  "${blkdev}"

# Shred the temporary key since we don't need it anymore
shred -z -u "${keyfile_tmp}"

printf '\n\n'
printf '%s\n' \
  'Next steps:' \
  '1. Create a recovery key for the lukshdrs partition!' \
  '2. Create root partition on SSD/HDD' \
  '3. Make backups of this USB drive.' \
  '' \
  '=========================================' \
  '| WRITE DOWN THE RECOVERY KEY ON PAPER! |' \
  '=========================================' \
  ''
