#!/usr/bin/sh
set -eu

if [ $# -ne 1 ]; then
  >&2 printf 'Usage: %s <device>\n' "${0##*/}"
  exit 2
fi
device="$1";shift

timeout=30

cat <<'EOF'
__     __    _     _ _              
\ \   / /   | |   (_) |             
 \ \_/ /   _| |__  _| | _____ _   _ 
  \   / | | | '_ \| | |/ / _ \ | | |
   | || |_| | |_) | |   <  __/ |_| |
   |_| \__,_|_.__/|_|_|\_\___|\__, |
                               __/ |
                              |___/ 

Insert your hardware security token to continue booting...
EOF

if udevadm wait --timeout 3 "${device}"; then
  >&2 printf 'Found %s\n' "${device}"
  exit 0
fi

while ! udevadm wait --timeout "${timeout}" --settle "${device}"
do
  >&2 printf 'Waiting for FIDO2 token...\n'
done
