#!/usr/bin/sh
set -eu

if [ $# -lt 1 ]; then
  printf 'Usage: %s <output-dir> [early-dir] [late-dir]\n' "${0##*/}"
  exit 2
fi

outdir="$1";shift
lukshdrs_path="/run/spork/lukshdrs/"
if ! [ -d "${lukshdrs_path}" ]; then
  printf '%s: Missing %s, ignored\n' "${0##*/}" "${lukshdrs_path}"
  exit 0
fi

mkdir -p "${outdir}/cryptsetup.target.wants/"

lsblk -o PARTUUID -rn | ( while read partuuid; do
  if ! [ -f "${lukshdrs_path}/${partuuid}.luks" ]; then
    continue
  fi
  partuuid_escaped="$(systemd-escape "${partuuid}")"
  luks_name="luks-part-${partuuid}"
  luks_name_escaped="$(systemd-escape "${luks_name}")"
  mkdir -p "${outdir}/blockdev@dev-mapper-${luks_name_escaped}.wants"
  ln -sf "../lukshdrs-cryptsetup@${partuuid_escaped}.service" \
    "${outdir}/blockdev@dev-mapper-${luks_name_escaped}.wants/"
  ln -sf "../lukshdrs-cryptsetup@${partuuid_escaped}.service" \
    "${outdir}/cryptsetup.target.wants/"
done )
